FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["MovieTicket.Api/MovieTicket.WebApi.csproj", "MovieTicket.Api/"]
RUN dotnet restore "MovieTicket.Api/MovieTicket.WebApi.csproj"
COPY . .
WORKDIR "/src/MovieTicket.Api"
RUN dotnet build "MovieTicket.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MovieTicket.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MovieTicket.WebApi.dll"]